/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class VistaRegistrar_Empleado extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistar_E
     */
    public VistaRegistrar_Empleado() {
        initComponents();
        txtPersona.setEnabled(false);
        
    }

    public JButton getBtnRegistrarE() {
        return btnRegistrarE;
    }

    public void setBtnRegistrarE(JButton btnRegistrarE) {
        this.btnRegistrarE = btnRegistrarE;
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public void setBtnRegresar(JButton btnRegresar) {
        this.btnRegresar = btnRegresar;
    }

    public JDateChooser getFechaContrato() {
        return fechaContrato;
    }

    public void setFechaContrato(JDateChooser fechaContrato) {
        this.fechaContrato = fechaContrato;
    }

    public JLabel getLblCargo() {
        return lblCargo;
    }

    public void setLblCargo(JLabel lblCargo) {
        this.lblCargo = lblCargo;
    }

    public JLabel getLblCedula() {
        return lblCedula;
    }

    public void setLblCedula(JLabel lblCedula) {
        this.lblCedula = lblCedula;
    }

    public JLabel getLblFecha() {
        return lblFecha;
    }

    public void setLblFecha(JLabel lblFecha) {
        this.lblFecha = lblFecha;
    }

    public JLabel getLblFondo() {
        return lblFondo;
    }

    public void setLblFondo(JLabel lblFondo) {
        this.lblFondo = lblFondo;
    }

    public JLabel getLblPersona() {
        return lblPersona;
    }

    public void setLblPersona(JLabel lblPersona) {
        this.lblPersona = lblPersona;
    }

    public JLabel getLblSueldo() {
        return lblSueldo;
    }

    public void setLblSueldo(JLabel lblSueldo) {
        this.lblSueldo = lblSueldo;
    }

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }


    public JTextField getTxtCedula() {
        return txtCedula;
    }

    public void setTxtCedula(JTextField txtCedula) {
        this.txtCedula = txtCedula;
    }

    public JTextField getTxtPersona() {
        return txtPersona;
    }

    public void setTxtPersona(JTextField txtPersona) {
        this.txtPersona = txtPersona;
    }

    public JTextField getTxtSueldo() {
        return txtSueldo;
    }

    public void setTxtSueldo(JTextField txtSueldo) {
        this.txtSueldo = txtSueldo;
    }

    public JComboBox<String> getCb_cargo() {
        return cb_cargo;
    }

    public void setCb_cargo(JComboBox<String> cb_cargo) {
        this.cb_cargo = cb_cargo;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblPersona = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblSueldo = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        fechaContrato = new com.toedter.calendar.JDateChooser();
        txtPersona = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        btnRegistrarE = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        cb_cargo = new javax.swing.JComboBox<>();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblTitulo.setText("REGISTRO DE  EMPLEADOS");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblCedula.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblCedula.setText("Cedula");
        getContentPane().add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        lblPersona.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblPersona.setText("Persona");
        getContentPane().add(lblPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        lblCargo.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblCargo.setText("Cargo");
        getContentPane().add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        lblFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblFecha.setText("Fecha de Contrato");
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        lblSueldo.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblSueldo.setText("Sueldo");
        getContentPane().add(lblSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        txtSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoActionPerformed(evt);
            }
        });
        getContentPane().add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 160, 30));
        getContentPane().add(fechaContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 130, 30));
        getContentPane().add(txtPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 160, 30));

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 160, 30));

        btnRegistrarE.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnRegistrarE.setText("Registrar Empleado");
        btnRegistrarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 210, 50));

        btnRegresar.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnRegresar.setText("Regresar");
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 130, 40));

        cb_cargo.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        cb_cargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        getContentPane().add(cb_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 160, -1));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 540, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnRegistrarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistrar_Empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarE;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cb_cargo;
    private com.toedter.calendar.JDateChooser fechaContrato;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPersona;
    private javax.swing.JLabel lblSueldo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtPersona;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
